# Spring Cloud Gateway server port
server:
  port: 7070
management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s
        pool:
          max-idle-time: 20
      metrics:
        enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
  pid:
    file: ${instance.pid}
---
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: local
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  auth-url: http://localhost:8080
  smart-admin-url: http://localhost:8081
  smart-admin-lrc-url: http://localhost:8082
  smart-admin-cpc-url: http://localhost:8083
  lrc-app-url: http://localhost:8084
  cpc-app-url: http://localhost:8085
  lrc-token-ignore: /api/v1/lrc/captcha/siteverify,/api/v1/lrc/scam/mail,/api/v1/lrc/user/join,/api/v1/lrc/user/join/certification,/api/v1/lrc/user/password/reset,/api/v1/lrc/user/password/reset/email,/api/v1/lrc/user/otp/init,/api/v1/lrc/user/otp/reset,/api/v1/lrc/user/otp/reset2
---
spring:
  config:
    import: classpath:aws-properties-eks-dev.yml
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  auth-url: http://k8s-systemsd-systemsa-b1008c664c-a3ca74a448432ee0.elb.ap-northeast-2.amazonaws.com
  smart-admin-url: http://k8s-systemsd-systemsm-3411cecba4-a185780c02b3ce0f.elb.ap-northeast-2.amazonaws.com
  smart-admin-lrc-url: http://k8s-systemsd-lrcmngap-6f8cba9e8e-5345f9a61df958fe.elb.ap-northeast-2.amazonaws.com
  smart-admin-cpc-url: http://k8s-systemsd-cpcmngap-b5f81d5545-2ecde87097b8d7bf.elb.ap-northeast-2.amazonaws.com
  lrc-app-url: http://k8s-systemsd-lrcappap-51a49fed08-97638021b6a67650.elb.ap-northeast-2.amazonaws.com
  cpc-app-url: http://k8s-systemsd-cpcappap-0fd4253b97-c2bdae0b9ed776ca.elb.ap-northeast-2.amazonaws.com
  lrc-token-ignore: /api/v1/lrc/captcha/siteverify,/api/v1/lrc/scam/mail,/api/v1/lrc/user/join,/api/v1/lrc/user/join/certification,/api/v1/lrc/user/password/reset,/api/v1/lrc/user/password/reset/email,/api/v1/lrc/user/otp/init,/api/v1/lrc/user/otp/reset,/api/v1/lrc/user/otp/reset2
---
spring:
  config:
    import: classpath:aws-properties-eks-prod.yml
    activate:
      on-profile: eks-prod
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  auth-url: http://k8s-systemsp-systemsa-e02c378086-acc7c1e658dd7475.elb.ap-northeast-2.amazonaws.com
  smart-admin-url: http://k8s-systemsp-systemsm-44af8aebfc-fdd7585d563eeb6b.elb.ap-northeast-2.amazonaws.com
  smart-admin-lrc-url: http://k8s-systemsd-lrcmngap-6f8cba9e8e-5345f9a61df958fe.elb.ap-northeast-2.amazonaws.com
  smart-admin-cpc-url: http://k8s-systemsp-cpcmngap-4b257d6ab0-ed1404229b40ed19.elb.ap-northeast-2.amazonaws.com
  lrc-app-url: http://k8s-systemsd-lrcappap-51a49fed08-97638021b6a67650.elb.ap-northeast-2.amazonaws.com
  cpc-app-url: http://k8s-systemsd-cpcappap-0fd4253b97-c2bdae0b9ed776ca.elb.ap-northeast-2.amazonaws.com
  lrc-token-ignore: /api/v1/lrc/captcha/siteverify,/api/v1/lrc/scam/mail,/api/v1/lrc/user/join,/api/v1/lrc/user/join/certification,/api/v1/lrc/user/password/reset,/api/v1/lrc/user/password/reset/email,/api/v1/lrc/user/otp/init,/api/v1/lrc/user/otp/reset,/api/v1/lrc/user/otp/reset2
---
spring:
  config:
    import: classpath:aws-properties-dev.yml
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  auth-url: http://bs-dev-sadmin-auth-api-intnlb-c300cbc61c2d8c1d.elb.ap-northeast-2.amazonaws.com
  smart-admin-url: http://bs-dev-sadmin-mng-api-intnlb-b056ca7212253ec4.elb.ap-northeast-2.amazonaws.com
  smart-admin-lrc-url: http://bs-dev-lrc-mng-api-intnlb-2946b43f0595d295.elb.ap-northeast-2.amazonaws.com
  smart-admin-cpc-url: http://bs-dev-cpc-mng-api-intnlb-35421a7834815ba8.elb.ap-northeast-2.amazonaws.com
  lrc-app-url: http://bs-dev-lrc-app-api-intnlb-22b0aada38b8e44f.elb.ap-northeast-2.amazonaws.com
  cpc-app-url: http://bs-dev-cpc-app-api-intnlb-0e432ee06a0e5273.elb.ap-northeast-2.amazonaws.com
  lrc-token-ignore: /api/v1/lrc/captcha/siteverify,/api/v1/lrc/scam/mail,/api/v1/lrc/user/join,/api/v1/lrc/user/join/certification,/api/v1/lrc/user/password/reset,/api/v1/lrc/user/password/reset/email,/api/v1/lrc/user/otp/init,/api/v1/lrc/user/otp/reset,/api/v1/lrc/user/otp/reset2
---
spring:
  config:
    import: classpath:aws-properties-qa.yml
    activate:
      on-profile: qa
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  auth-url: http://bs-qa-sadmin-auth-api-intnlb-c990ec0a5ab8fa84.elb.ap-northeast-2.amazonaws.com
  smart-admin-url: http://bs-qa-sadmin-mng-api-intnlb-38dd38162ef2d7e3.elb.ap-northeast-2.amazonaws.com
  smart-admin-lrc-url: http://bs-qa-lrc-mng-api-intnlb-218b4d31d3fe6225.elb.ap-northeast-2.amazonaws.com
  smart-admin-cpc-url: http://bs-qa-cpc-mng-api-intnlb-e7286b5ad5e10d14.elb.ap-northeast-2.amazonaws.com
  lrc-app-url: http://bs-qa-lrc-app-api-intnlb-5f2e6b73955e1314.elb.ap-northeast-2.amazonaws.com
  cpc-app-url: http://bs-qa-cpc-app-api-intnlb-77c5d2580a3aa06e.elb.ap-northeast-2.amazonaws.com
  lrc-token-ignore: /api/v1/lrc/captcha/siteverify,/api/v1/lrc/scam/mail,/api/v1/lrc/user/join,/api/v1/lrc/user/join/certification,/api/v1/lrc/user/password/reset,/api/v1/lrc/user/password/reset/email,/api/v1/lrc/user/otp/init,/api/v1/lrc/user/otp/reset,/api/v1/lrc/user/otp/reset2
---
spring:
  config:
    import: classpath:aws-properties-prod.yml
    activate:
      on-profile: prod
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  auth-url: http://bs-sadmin-auth-api-intnlb-bc558335f7e6e591.elb.ap-northeast-2.amazonaws.com
  smart-admin-url: http://bs-sadmin-mng-api-intnlb-81638ad950a3faac.elb.ap-northeast-2.amazonaws.com
  smart-admin-lrc-url: http://bs-lrc-mng-api-intnlb-de47854c0c46cc98.elb.ap-northeast-2.amazonaws.com
  smart-admin-cpc-url: http://bs-cpc-mng-api-intnlb-a7b27e9ac37c95fd.elb.ap-northeast-2.amazonaws.com
  lrc-app-url: http://bs-lrc-app-api-intnlb-1f9ef12d58cd84a1.elb.ap-northeast-2.amazonaws.com
  cpc-app-url: http://bs-cpc-app-api-intnlb-35e666af71367f3f.elb.ap-northeast-2.amazonaws.com
  lrc-token-ignore: /api/v1/lrc/captcha/siteverify,/api/v1/lrc/scam/mail,/api/v1/lrc/user/join,/api/v1/lrc/user/join/certification,/api/v1/lrc/user/password/reset,/api/v1/lrc/user/password/reset/email,/api/v1/lrc/user/otp/init,/api/v1/lrc/user/otp/reset,/api/v1/lrc/user/otp/reset2
---
# Spring cloud gateway setup
#spring:
#  cloud:
#    gateway:
#      # gateway common filter
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway GlobalFilter
#            preLogger: true
#            postLogger: true
#       #Route definition
#       #ID, Destination(uri), Predicate, filter definition
#      routes:
#        - id: user-service
#          # destination
#          uri: http://localhost:8080
#          # Condition
#          predicates:
#            - Path=/user/**
#          # Filter
#          filters:
#            - name: UserFilter
#              args:
#                baseMessage: UserFilter apply
#                preLogger: true
#                postLooger: true
#            - RewritePath=/user/(?<path>.*),/api/v1/user/$\{path}
#        - id: adm-service
#          # destination
#          uri: http://localhost:8080
#          # Condition
#          predicates:
#            - Path=/adm/**
#          # Filter
#          filters:
#            - name: UserFilter
#              args:
#                baseMessage: UserFilter apply
#                preLogger: true
#                postLooger: true
#            - RewritePath=/adm/(?<path>.*),/api/v1/adm/$\{path}
#        - id: auth-service
#          # destination
#          uri: http://localhost:8080
#          # Condition
#          predicates:
#            - Path=/auth/**
#          # Filter
#          filters:
#            - name: AuthFilter
#              args:
#                baseMessage: AuthFilter apply
#                preLogger: true
#                postLooger: true
#        - id: api-service
#          uri: http://localhost:9092
#          predicates:
#            - Path=/api/**
#          filters:
#            - name: ApiFilter
#              args:
#                baseMessage: ApiFilter apply
#                preLogger: true
#                postLogger: true